import { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import {
  ApolloClient,
  InMemoryCache,
  gql
} from "@apollo/client";

import Layout from '@components/Layout';
import Container from '@components/Container';
import Button from '@components/Button';

import styles from '@styles/Home.module.scss'

export default function Home({ products, allegiances }) {
  const [activeAllegiance, setActiveAllegiance] = useState();

  let activeProducts = products;

  if ( activeAllegiance ) {
    activeProducts = activeProducts.filter(({ allegiances }) => {
      const allegianceIds = allegiances.map(({ slug }) => slug);
      return allegianceIds.includes(activeAllegiance);
    })
  }

  console.log(activeAllegiance)
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <h1 className="sr-only">Hyper Bros. Trading Cards</h1>

        <div className={styles.allegiances}>
          <h2>Filter by Allegiance</h2>
          <ul>
            {allegiances.map(allegiance => {
              const isActive = allegiance.slug === activeAllegiance;
              let allegianceClassName;
              if ( isActive ) {
                allegianceClassName = styles.allegianceIsActive;
              }
              return (
                <li key={allegiance.id}>
                  <Button className={allegianceClassName} color="yellow" onClick={() => setActiveAllegiance(allegiance.slug)}>
                    {allegiance.name}
                  </Button>
                </li>
              )
            })}
            <li>
              <Button className={!activeAllegiance && styles.allegianceIsActive} color="yellow" onClick={() => setActiveAllegiance(undefined)}>
                View All
              </Button>
            </li>
          </ul>
        </div>

        <h2 className="sr-only">Available Cards</h2>
        <ul className={styles.products}>
          {activeProducts.map(product => {
            const { featuredImage } = product;
            return (
              <li key={product.id}>
                <Link href={`/products/${product.slug}`}>
                  <a>
                    <div className={styles.productImage}>
                      <Image width={featuredImage.mediaDetails.width} height={featuredImage.mediaDetails.height} src={featuredImage.sourceUrl} alt={featuredImage.altText} />
                    </div>
                    <h3 className={styles.productTitle}>
                      { product.title }
                    </h3>
                    <p className={styles.productPrice}>
                      ${ product.productPrice }
                    </p>
                  </a>
                </Link>
                <p>
                  <Button
                    className="snipcart-add-item"
                    data-item-id={product.productId}
                    data-item-price={product.productPrice}
                    data-item-url="/"
                    data-item-description=""
                    data-item-image={featuredImage.sourceUrl}
                    data-item-name={product.title}
                    data-item-max-quantity={1}
                  >
                    Add to Cart
                  </Button>
                </p>
              </li>
            )
          })}
        </ul>
      </Container>
    </Layout>
  )
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: 'https://hyperbros.wpengine.com/graphql',
    cache: new InMemoryCache()
  });

  const response = await client.query({
    query: gql`
      query AllProductsAndAllegiances {
        products {
          edges {
            node {
              id
              content
              title
              uri
              product {
                productPrice
                productId
              }
              slug
              featuredImage {
                node {
                  altText
                  sourceUrl
                  mediaDetails {
                    height
                    width
                  }
                }
              }
              allegiances {
                edges {
                  node {
                    id
                    name
                    slug
                  }
                }
              }
            }
          }
        }
        allegiances {
          edges {
            node {
              id
              name
              slug
            }
          }
        }
      }
    `
  });

  const products = response.data.products.edges.map(({ node }) => {
    const data = {
      ...node,
      ...node.product,
      featuredImage: {
        ...node.featuredImage.node
      },
      allegiances: node.allegiances.edges.map(({ node }) => node)
    }
    return data;
  })

  const allegiances = response.data.allegiances.edges.map(({ node }) => node);

  return {
    props: {
      products,
      allegiances
    }
  }
}